### ISSUE TITLE
Using custom execution context

### ISSUE THREAD

**Issue by ceecer1** [git-josip/reactive-play-scala-akka-slick-guice-domain_validation-seed#1]
Just wanted to have a more understanding and clarity on why you were trying to create a new execution context with the commented code in com.josip.reactiveluxury.configuration.CustomExecutionContext

Thanks in advance !

**Comment by git-josip** [comment]
Hey Shishir,

I was trying to create new custom execution context as in production code I would not like use global one provided implicitly which has number of worker threads equal to the number of available processors. 
scala.concurrent.ExecutionContext.Implicits.global context is described in class documentation : 

```
/**
     * The implicit global `ExecutionContext`. Import `global` when you want to provide the global
     * `ExecutionContext` implicitly.
     *
     * The default `ExecutionContext` implementation is backed by a work-stealing thread pool. By default,
     * the thread pool uses a target number of worker threads equal to the number of
     * [[https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#availableProcessors-- available processors]].
     */
    implicit lazy val global: ExecutionContextExecutor = impl.ExecutionContextImpl.fromExecutor(null: Executor)
```

In play 2.5.x using implicitly context should be replaced by providing context using dependency injection.
I will do update on this seed to behave like that.

Our application can use multiple execution context i.e. we can have decoupled execution context for DB access and separate one for other things. 
Best practices with execution contexts are described in play documentation: https://www.playframework.com/documentation/2.5.x/ThreadPools#many-specific-thread-pools 

Easiest way to create execution context is with app properties: 

```
object Contexts {
  implicit val simpleDbLookups: ExecutionContext = akkaSystem.dispatchers.lookup("contexts.simple-db-lookups")
  implicit val expensiveDbLookups: ExecutionContext = akkaSystem.dispatchers.lookup("contexts.expensive-db-lookups")
  implicit val dbWriteOperations: ExecutionContext = akkaSystem.dispatchers.lookup("contexts.db-write-operations")
  implicit val expensiveCpuOperations: ExecutionContext = akkaSystem.dispatchers.lookup("contexts.expensive-cpu-operations")
}
```

configured as: 

```
contexts {
  simple-db-lookups {
    executor = "thread-pool-executor"
    throughput = 1
    thread-pool-executor {
      fixed-pool-size = 20
    }
  }
  expensive-db-lookups {
    executor = "thread-pool-executor"
    throughput = 1
    thread-pool-executor {
      fixed-pool-size = 20
    }
  }
  db-write-operations {
    executor = "thread-pool-executor"
    throughput = 1
    thread-pool-executor {
      fixed-pool-size = 10
    }
  }
  expensive-cpu-operations {
    fork-join-executor {
      parallelism-max = 2
    }
  }
}
```

Best regards,
Josip
